Repository litmuschaos/litmus-ui, pull requests merged in 2021-03, with the labels that each got.

#15 Updating Next to latest dev
  .circleci/config.yml
  package.json
  rollup.config.js
  src/core/InputField/__tests__/InputField.test.tsx
  src/core/ProgressBar/__tests__/ProgressBar.test.tsx
  src/core/QuickActionCard/QuickActionCard.stories.tsx
  src/core/QuickActionCard/QuickActionCard.tsx
  src/core/QuickActionCard/__tests__/QuickActionCard.test.tsx
  src/core/QuickActionCard/base.ts
  src/core/QuickActionCard/index.ts
  src/core/QuickActionCard/styles.ts
  src/core/QuickActionCard/testData.ts
  src/core/RadioButton/__tests__/RadioButton.test.tsx
  src/core/Search/__tests__/Search.test.tsx
  src/core/Text/EditableText/__tests__/EditableText.test.tsx
  src/core/index.ts
  src/lab/Graphs/LegendTable/LegendTable.stories.tsx
  src/lab/Graphs/LegendTable/LegendTable.tsx
  src/lab/Graphs/LegendTable/base.ts
  src/lab/Graphs/LegendTable/index.ts
  src/lab/Graphs/LegendTable/style.ts
  src/lab/Graphs/LineAreaGraph/ComputationGraph.tsx
  src/lab/Graphs/LineAreaGraph/FilteredLineAreaGraph.tsx
  src/lab/Graphs/LineAreaGraph/LineAreaGraph.stories.tsx
  src/lab/Graphs/LineAreaGraph/LineAreaGraph.tsx
  src/lab/Graphs/LineAreaGraph/PlotLineAreaGraph.tsx
  src/lab/Graphs/LineAreaGraph/base.ts
  src/lab/Graphs/LineAreaGraph/index.ts
  src/lab/Graphs/LineAreaGraph/plotLineAreaGraphStyles.ts
  src/lab/Graphs/LineAreaGraph/styles.ts
  src/lab/Graphs/LineAreaGraph/testData.ts
  src/lab/Graphs/RadialChart/RadialChart.tsx
  src/lab/Graphs/RadialChart/RaidalChart.stories.tsx
  src/lab/Graphs/RadialChart/base.ts
  src/lab/Graphs/RadialChart/index.ts
  src/lab/Graphs/RadialChart/styles.ts
  src/lab/Graphs/RadialChart/testData.ts
  yarn.lock
Labels: update

#16 Updating Master from Next
  .circleci/config.yml
  package.json
  rollup.config.js
  src/core/InputField/__tests__/InputField.test.tsx
  src/core/ProgressBar/__tests__/ProgressBar.test.tsx
  src/core/QuickActionCard/QuickActionCard.stories.tsx
  src/core/QuickActionCard/QuickActionCard.tsx
  src/core/QuickActionCard/__tests__/QuickActionCard.test.tsx
  src/core/QuickActionCard/base.ts
  src/core/QuickActionCard/index.ts
  src/core/QuickActionCard/styles.ts
  src/core/QuickActionCard/testData.ts
  src/core/RadioButton/__tests__/RadioButton.test.tsx
  src/core/Search/__tests__/Search.test.tsx
  src/core/Text/EditableText/__tests__/EditableText.test.tsx
  src/core/index.ts
  src/lab/Graphs/LegendTable/LegendTable.stories.tsx
  src/lab/Graphs/LegendTable/LegendTable.tsx
  src/lab/Graphs/LegendTable/base.ts
  src/lab/Graphs/LegendTable/index.ts
  src/lab/Graphs/LegendTable/style.ts
  src/lab/Graphs/LineAreaGraph/ComputationGraph.tsx
  src/lab/Graphs/LineAreaGraph/FilteredLineAreaGraph.tsx
  src/lab/Graphs/LineAreaGraph/LineAreaGraph.stories.tsx
  src/lab/Graphs/LineAreaGraph/LineAreaGraph.tsx
  src/lab/Graphs/LineAreaGraph/PlotLineAreaGraph.tsx
  src/lab/Graphs/LineAreaGraph/base.ts
  src/lab/Graphs/LineAreaGraph/index.ts
  src/lab/Graphs/LineAreaGraph/plotLineAreaGraphStyles.ts
  src/lab/Graphs/LineAreaGraph/styles.ts
  src/lab/Graphs/LineAreaGraph/testData.ts
  src/lab/Graphs/RadialChart/RadialChart.tsx
  src/lab/Graphs/RadialChart/RaidalChart.stories.tsx
  src/lab/Graphs/RadialChart/base.ts
  src/lab/Graphs/RadialChart/index.ts
  src/lab/Graphs/RadialChart/styles.ts
  src/lab/Graphs/RadialChart/testData.ts
  yarn.lock
Labels: update

#17 Upgrading Node image version
  .circleci/config.yml
Labels: enhancement

#26 Removing DayJS from Peer Dependency + Adding depcheck CI
  .circleci/config.yml
  package.json
Labels: bug

#27 Removing react-spring as peer dependency
  package.json
Labels: update

#31 Components update
  package.json
  src/core/Link/Link.stories.tsx
  src/core/Link/Link.tsx
  src/core/Link/__tests__/Link.test.tsx
  src/core/Link/base.ts
  src/core/Link/index.ts
  src/core/Link/styles.ts
  src/core/Modal/Modal.stories.tsx
  src/core/Modal/Modal.tsx
  src/core/Modal/styles.ts
  src/core/index.ts
  src/lab/Graphs/LegendTable/LegendTable.tsx
  src/lab/Graphs/LegendTable/base.ts
  src/lab/Graphs/LegendTable/index.ts
  src/lab/Graphs/LegendTable/style.ts
  src/lab/Graphs/LegendTable/testData.ts
  src/lab/Graphs/LineAreaGraph/ComputationGraph.tsx
  src/lab/Graphs/LineAreaGraph/FilteredLineAreaGraph.tsx
  src/lab/Graphs/LineAreaGraph/LineAreaGraph.tsx
  src/lab/Graphs/LineAreaGraph/base.ts
  src/lab/Graphs/LineAreaGraph/styles.ts
  src/lab/Graphs/PassFailBar/PassFailBar.stories.tsx
  src/lab/Graphs/PassFailBar/PassFailBar.tsx
  src/lab/Graphs/PassFailBar/index.ts
  src/lab/Graphs/PassFailBar/styles.ts
  src/lab/Graphs/RadialChart/RadialChart.tsx
  src/lab/Graphs/RadialChart/RaidalChart.stories.tsx
  src/lab/Graphs/RadialChart/base.ts
  src/lab/Graphs/RadialChart/index.ts
  src/lab/Graphs/RadialChart/styles.ts
  src/lab/Graphs/RadialGraphs/RadialChart/RadialChart.stories.tsx
  src/lab/Graphs/RadialGraphs/RadialChart/RadialChart.tsx
  src/lab/Graphs/RadialGraphs/RadialChart/index.ts
  src/lab/Graphs/RadialGraphs/RadialChart/styles.ts
  src/lab/Graphs/RadialGraphs/RadialChart/testData.ts
  src/lab/Graphs/RadialGraphs/RadialProgressChart/RadialProgressChart.stories.tsx
  src/lab/Graphs/RadialGraphs/RadialProgressChart/RadialProgressChart.tsx
  src/lab/Graphs/RadialGraphs/RadialProgressChart/index.ts
  src/lab/Graphs/RadialGraphs/RadialProgressChart/styles.ts
  src/lab/Graphs/RadialGraphs/RadialProgressChart/testData.ts
  src/lab/Graphs/RadialGraphs/base.ts
  src/lab/Graphs/RadialGraphs/index.ts
  src/lab/Graphs/index.ts
  src/lab/Tabs/Tabs.stories.tsx
  src/lab/Tabs/Tabs.tsx
  src/lab/Tabs/__tests__/Tabs.test.tsx
  src/lab/Tabs/base.ts
  src/lab/Tabs/index.ts
  src/lab/Tabs/styles.ts
  src/lab/index.ts
Labels: review-requested
